name: Ubuntu ssh Virtual Machine (NPS)
on: 
  workflow_dispatch:

defaults:
  run:
    shell: bash 

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
#    - name: If failed, means ok
#      run: ./not-exist-file.sh it bloke build
    - name: Preparing Linux Environment
      run: sudo apt-get update
    - name: Setting Up the Ubuntu Environment
    #  if: ${{ failure() }}
      run: bash linux-ssh.sh
      env:
        LINUX_USER_PASSWORD: ${{ secrets.LINUX_USER_PASSWORD }}
        LINUX_MACHINE_NAME: ${{ secrets.LINUX_MACHINE_NAME }}
        LINUX_USERNAME: ${{ secrets.LINUX_USERNAME }}
    - name: Setting Up the NPS
    #  if: ${{ failure() }}
      run: |
        wget -q https://github.com/ehang-io/nps/releases/download/v0.26.10/linux_amd64_client.tar.gz
        tar -xzf linux_amd64_client.tar.gz
        chmod +x ./npc
        sudo ./npc install -server="$NPS_ADDRESS" -vkey="$NPS_AUTH_TOKEN" -type=tcp
        sudo rm -rf linux_amd64_client.tar.gz conf
        sudo npc start
      env:
        NPS_AUTH_TOKEN: ${{ secrets.NPS_AUTH_TOKEN }}
        NPS_ADDRESS: ${{ secrets.NPS_ADDRESS }}
    - name: Keep Running Ubuntu System and keepAlive
     # if: ${{ failure() }}
      run: sleep 6h
