name: Ubuntu ssh Virtual Machine (NPS)
on: 
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'
defaults:
  run:
    shell: bash
    
    
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
#    - name: If failed, means ok
#      run: ./not-exist-file.sh it bloke build
    - name: Preparing Linux Environment
      run: sudo apt-get update
    - name: Setting Up the Ubuntu Environment
    #  if: ${{ failure() }}
      run: bash linux-ssh.sh
      env:
        LINUX_USER_PASSWORD: ${{ secrets.LINUX_USER_PASSWORD }}
        LINUX_MACHINE_NAME: ${{ secrets.LINUX_MACHINE_NAME }}
        LINUX_USERNAME: ${{ secrets.LINUX_USERNAME }}
    - name: Setting Up the NPS
    #  if: ${{ failure() }}
      run: |
        wget -q https://github.com/ehang-io/nps/releases/download/v0.26.10/linux_amd64_client.tar.gz
        tar -xzf linux_amd64_client.tar.gz
        chmod +x ./npc
        sudo ./npc install -server="$NPS_ADDRESS" -vkey="$NPS_AUTH_TOKEN" -type=tcp
        sudo rm -rf linux_amd64_client.tar.gz conf
        sudo npc start
      env:
        NPS_AUTH_TOKEN: ${{ secrets.NPS_AUTH_TOKEN }}
        NPS_ADDRESS: ${{ secrets.NPS_ADDRESS }}
    - name: Setting Up the XRay
    #  if: ${{ failure() }}
      run: |
        sudo bash -c "$(curl -L https://github.com/XTLS/Xray-install/raw/main/install-release.sh)" @ install -u root
        echo $XRAY_CONFIG | sudo tee /usr/local/etc/xray/config.json
        sudo openssl ecparam -name prime256v1 -genkey -out /home/private.key
        sudo openssl req -new -x509 -days 7305 -key /home/private.key -out /home/fullchain.crt -subj "/C=CN/ST=Beijing/L=Beijing/O=Beijing OnlineJudge Technology Co., Ltd./OU=Service Infrastructure Department/CN=`hostname`"
        sudo systemctl restart xray
      env:
        XRAY_CONFIG: ${{ secrets.XRAY_CONFIG }}
    - name: Keep Running Ubuntu System and keepAlive
     # if: ${{ failure() }}
      run: sleep 6h
