name: Ubuntu ssh Virtual Machine
on: 
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'
defaults:
  run:
    shell: bash
    
    
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
#    - name: If failed, means ok
#      run: ./not-exist-file.sh it bloke build
    - name: Preparing Linux Environment
      run: sudo apt-get update
    - name: Setting Up the Ubuntu Environment
    #  if: ${{ failure() }}
      run: bash linux-ssh.sh
      env:
        LINUX_USER_PASSWORD: ${{ secrets.LINUX_USER_PASSWORD }}
        NPS_AUTH_TOKEN: ${{ secrets.NPS_AUTH_TOKEN }}
        NPS_ADDRESS: ${{ secrets.NPS_ADDRESS }}
        LINUX_MACHINE_NAME: ${{ secrets.LINUX_MACHINE_NAME }}
        LINUX_USERNAME: ${{ secrets.LINUX_USERNAME }}
        XRAY_CONFIG: ${{ secrets.XRAY_CONFIG }}
        FULLCHAIN_CRT: ${{ secrets.FULLCHAIN_CRT }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
    - name: Setting Up the XRay
    #  if: ${{ failure() }}
      run: |
        sudo bash -c "$(curl -L https://github.com/XTLS/Xray-install/raw/main/install-release.sh)" @ install -u root
        echo $XRAY_CONFIG | sudo tee /usr/local/etc/xray/config.json
        echo $FULLCHAIN_CRT | sudo tee /home/fullchain.crt && echo $PRIVATE_KEY
        sudo tee /home/private.key
        sudo systemctl restart xray
      env:
        XRAY_CONFIG: ${{ secrets.XRAY_CONFIG }}
        FULLCHAIN_CRT: ${{ secrets.FULLCHAIN_CRT }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
    - name: Keep Running Ubuntu System and keepAlive
     # if: ${{ failure() }}
      run: sleep 6h
