name: MacOS Virtual Machine
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    name: MacOS Build
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setting Up the MacOS Environment
      env:
        NPS_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        NPS_ADDRESS: ${{ secrets.NPS_ADDRESS }}
        MAC_USER_PASSWORD: ${{ secrets.MAC_USER_PASSWORD }}
        VNC_PASSWORD: ${{ secrets.VNC_PASSWORD }}
        MAC_REALNAME: ${{ secrets.MAC_REALNAME }}
      run: source macos-run.sh "$MAC_USER_PASSWORD" "$VNC_PASSWORD" "$NGROK_AUTH_TOKEN" "$MAC_REALNAME" "$NPS_ADDRESS"
    - name: Connecting MacOS with Ngrok to VNC Server
      run: sudo cat /var/log/npc.log
    - name: Keep Running MacOS System and keepAlive
      uses: mxschmitt/action-tmate@v2
