name: Windows Server 2019

on: 
  workflow_dispatch:

jobs:
  build:
    name: Windows 10 Build
    runs-on: windows-latest
    timeout-minutes: 9999
    
    steps:
    - name: Creating Local User
      run: |
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText $Env:WINDOWS_USER_PASSWORD -Force)
      env:
        WINDOWS_USER_PASSWORD: ${{ secrets.WINDOWS_USER_PASSWORD }}
    - name: Download
      run: |
       Invoke-WebRequest https://github.com/RealKoolisw/VirtualMachine-GithubAction/blob/main/resources/ngrok-stable-windows-amd64.zip?raw=true -OutFile ngrok.zip
       Invoke-WebRequest https://github.com/RealKoolisw/VirtualMachine-GithubAction/blob/main/resources/nssm.exe?raw=true -OutFile nssm.exe
       Invoke-WebRequest https://raw.githubusercontent.com/RealKoolisw/VirtualMachine-GithubAction/main/resources/windows-loop.bat -OutFile loop.bat
    - name: Extract
      run: Expand-Archive ngrok.zip
    - name: Copy NSSM & Ngrok to Windows Directory.
      run: | 
        copy nssm.exe C:\Windows\System32
        copy .\ngrok\ngrok.exe C:\Windows\System32
    - name: Auth
      run: |
        .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Installing Ngrok Process as a Windows Core Services
      run: |
        C:
        cd C:\Users\runneradmin\.ngrok2
        copy ngrok.yml C:\Windows\System32
        nssm install ngrok C:\Windows\System32\ngrok.exe start tcp 3389 --region=ap --config="C:\Windows\System32\ngrok.yml"
        nssm set ngrok Start SERVICE_AUTO_START
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - name: Enabing Networking Firewall
      run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - name: Setting up RDP TCP UserAuthentication
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Create Tunnel
      run: sc start ngrok
    - name: Looping Process
      run: ./ngrok/ngrok.exe tcp 3389 --region=ap
